default: &default
  adapter: postgresql
  encoding: unicode
  user: gm_root
  password: gmrootyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url-shorten-development

test:
  <<: *default
  database: url-shorten-test

production:
  <<: *default
  database: url-shorten-production
  username: url-shorten
  password: <%= ENV['URL-SHRTEN_DATABASE_PASSWORD'] %>
